force-app/main/default/objects/Trade__c/Trade__c.object-meta.xml
<CustomObject>
    <label>Trade</label>
    <nameField>
        <displayFormat>TR{0000000}</displayFormat>
        <label>Trade Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trade__c/fields/Buy_Currency__c.field-meta.xml
<CustomField>
    <fullName>Buy_Currency__c</fullName>
    <label>Buy Currency</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Trade__c/fields/Rate__c.field-meta.xml
<CustomField>
    <fullName>Rate__c</fullName>
    <label>Rate</label>
    <precision>12</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trade__c/fields/Sell_Currency__c.field-meta.xml
<CustomField>
    <fullName>Sell_Currency__c</fullName>
    <label>Sell Currency</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CurrencyController.cls
public with sharing class CurrencyController {

	@AuraEnabled(cacheable=true)
	public static CurrencyService.CurrencyDocumentResponseModel getCurrencyData() {
		try {
			CurrencyService.CurrencyDocumentResponseModel result = CurrencyService.getCurrencyResponse();
			return result;
		} catch( Exception e ) {
			throw new AuraHandledException( e.getMessage() );
		}
	}

	@AuraEnabled(cacheable=true)
	public static List<Trade__c> getExistingTrades() {
		List<Trade__c> tradesList = [
				SELECT Id,
						Sell_Currency__c,
						Sell_Amount__c,
						Buy_Currency__c,
						Buy_Amount__c,
						Rate__c,
						CreatedDate
				FROM Trade__c
				ORDER BY CreatedDate DESC
		];

		return tradesList;
	}

	@AuraEnabled
	public static CurrencyService.CurrencyCalculateResponseModel calculate( String currencyFrom, String currencyTo, String currencyAmount ) {
		CurrencyService.CurrencyCalculateResponseModel result = CurrencyService.getCalculationResultService( currencyFrom, currencyTo, currencyAmount );

		return result;
	}

	@AuraEnabled
	public static void createTrade( String sellCCY, String sellAmount, String buyCurrency, String buyAmount, String rate ) {
		try {
			Trade__c newTrade = new Trade__c();
			newTrade.Sell_Currency__c = sellCCY;
			newTrade.Sell_Amount__c = double.valueOf( sellAmount );
			newTrade.Buy_Currency__c = buyCurrency;
			newTrade.Buy_Amount__c = double.valueOf( buyAmount );
			newTrade.Rate__c = double.valueOf( rate );

			insert newTrade;
		} catch( Exception e ) {	
			System.debug('e: ' + e);
			throw new AuraHandledException( e.getMessage() );
		}
	}
}